# website settings
website:
  title: "Tommaso Crosta"
  favicon: img/favicon.png

  navbar:
    title: "Tommaso Crosta"
    pinned: true
    left:
      - text: "Research"
        href: Research/index.qmd
      - text: "Teaching"
        href: Teaching/index.qmd
      - text: "CV"
        href: cv/index.qmd
    right:
      - icon: twitter
        href: https://x.com/TommasoCrosta
      - icon: linkedin
        href: https://www.linkedin.com/in/tommaso-crosta-31873817b/
      - icon: envelope
        aria-label: email
        href: "mailto:tommaso.crosta@phd.unibocconi.it"

  page-footer:
    left: "Tommaso Crosta"
    right: "[Email](mailto:tommaso.crosta@phd.unibocconi.it) | [LinkedIn](https://www.linkedin.com/in/tommaso-crosta-31873817b/)"

  search:
    location: navbar
    type: textbox

project:
  type: website
  output-dir: docs

  preview:
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme:
      - litera
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: false
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
